routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Contracts\Auth\Access\Gate;

Route::group(['middleware' => 'web'], function () {

    Route::auth();
    Route::get('/home', function () {
        return redirect('/');
    });

    Route::get('/student/dashboard', function () {
        $user = \Illuminate\Support\Facades\Auth::user();

        if (\Illuminate\Support\Facades\Auth::check()) {
            return view('subject.dashboard', compact('user'));
        } else {
            return redirect()->route('login');
        }

    })->name('student.dashboard');
    Route::get('/', 'HomeController@index');
    Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function () {
        Route::get('/', function () {
            return view('admin.index');
        });
        Route::get('/user', function () {
            return view('admin.user');
        });

        Route::resource('category', 'CategoryController');
        Route::get('results', 'SubjectController@getAllSubjectsResults')->name('subjects.results');
        Route::get('subject', 'SubjectController@getIndex')->name('subject.index');
        Route::get('subject/new', 'SubjectController@getNew')->name('subject.new');
        Route::get('subject/{id}', 'SubjectController@getQuestions')->name('subject.question');
        Route::post('subject/{id}/edit', 'SubjectController@postEditQuestion')->name('subject.question.post.edit');
        Route::post('subject/new', 'SubjectController@postNewSubject')->name('subject.new');
        Route::post('subject/{id}', 'SubjectController@postNewQuestion')->name('subject.post.new.question');
        Route::get('subject/{id}/edit', 'SubjectController@getEdit')->name('subject.question.edit');
        Route::get('subject/{id}/delete', 'SubjectController@getDelete')->name('subject.delete');
        Route::get('subject/{id}/delete/question', 'SubjectController@getDeleteQuestion')->name('subject.question.delete');
        Route::patch('subject/{id}/edit', 'SubjectController@patchEdit')->name('subject.question.patch.edit');
        Route::resource('subject', 'SubjectController', ['except' => ['result', 'save-question', 'before-exam', 'start-exam']]);
        Route::resource('user', 'UserController');
        Route::resource('difficulty', 'DifficultyLevelController');
        Route::resource('score', 'ScoreController');
    });
    Route::group(['prefix' => 'user', 'middleware' => 'user'], function () {
        Route::get('/', function () {
            return redirect('user/get/results');
        })->name('index.home');
        Route::get('result/{id}', 'SubjectController@getShowResultOfSubjectForGuest')->name('result');
        Route::post('subject/save-question-result/{id}', 'SubjectController@postSaveQuestionResult')->name('user.save-question');
        Route::get('subject/{id}/start', 'SubjectController@getBeforeStartTest')->name('before-exam');
        Route::get('subject/{id}/start-test', 'SubjectController@getStartTest')->name('start-exam');
        Route::get('get/results', 'SubjectController@getResults')->name('get.results');
        Route::get('get/progression/level', 'SubjectController@getUserProgressionLevel')->name('user.get.progression.level');


    });
    Route::group(['prefix' => 'teacher', 'middleware' => 'teacher'], function () {


        Route::resource('category', 'CategoryController');
        Route::get('subject', 'SubjectController@getIndex')->name('subject.index');
        Route::get('subject/new', 'SubjectController@getNew')->name('subject.new');
        Route::get('subject/{id}', 'SubjectController@getQuestions')->name('subject.question');
        Route::post('subject/{id}/edit', 'SubjectController@postEditQuestion')->name('subject.question.post.edit');
        Route::post('subject/new', 'SubjectController@postNewSubject')->name('subject.new');
        Route::post('subject/{id}', 'SubjectController@postNewQuestion')->name('subject.post.new.question');
        Route::get('subject/{id}/edit', 'SubjectController@getEdit')->name('subject.question.edit');
        Route::get('subject/{id}/delete', 'SubjectController@getDelete')->name('subject.delete');
        Route::get('subject/{id}/delete/question', 'SubjectController@getDeleteQuestion')->name('subject.question.delete');
        Route::patch('subject/{id}/edit', 'SubjectController@patchEdit')->name('subject.question.patch.edit');
        Route::resource('subject', 'SubjectController', ['except' => ['result', 'save-question', 'before-exam', 'start-exam']]);
        Route::resource('class', 'ClassesController');
        Route::get('get/results', 'SubjectController@getResults')->name('teacher.get.results');

        Route::get('get/progression/level', 'SubjectController@getProgressionLevel')->name('teacher.get.progression.level');


        Route::get('questions/createnew', 'QuestionsController@createnew')->name('questions.createnew');
        Route::post('questions/storequestion', 'QuestionsController@storequestion')->name('questions.storequestion');
        Route::post('questions/updatequestion/{id}', 'QuestionsController@updateQuestion')->name('questions.updatequestion');
        Route::get('questions', 'QuestionsController@Index')->name('questions.index');
        Route::get('questions/edit/{id}', 'QuestionsController@editQuestion')->name('questions.edit');


    });
    Route::get('profile/edit', 'UserController@profileEdit')->name('user.profile.edit');
    Route::post('profile/edit', 'UserController@profileUpdate')->name('user.profile.update');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name', 'status'];

    /* public function getStatusAttribute($value){
         return $this->attributes['status']?"Active":"Non";
     }*/

    public function subjects()
    {
        return $this->hasMany('App\Subject', 'category_id', 'id');
    }

    public function questions()
    {
        return $this->belongsToMany(Category::class, 'cat_questions', 'category_id', 'question_id')->withTimestamps()->as('cat_questions');
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Category;
use App\Http\Requests\CategoryRequest;

use Symfony\Component\HttpFoundation\Session\Flash;

class CategoryController extends Controller
{
    public function index()
    {
        $categories = Category::paginate(5);
        $title = 'Categories Listing';
        return view('category.index', compact('categories', 'title'));
    }

    public function create()
    {
        $title = "Create New Category";
        return view('category.new', compact('title'));
    }



    public function store(CategoryRequest $req)
    {

        Category::create($req->all());
        session()->flash('flash_mess', 'Category was created completely');
        return redirect(route('category.index'));
    }

    public function show(){

    }

    public function edit($id)
    {
        $category = Category::findOrFail($id);
        //dd($category);
        $title = "Edit Category '{$category->name}'";
        return view('category.edit', compact('category', 'title'));
    }

    public function update($id, CategoryRequest $req)
    {

        if ($req->get('status') == null)
            $req['status'] = 0;

        //dd($req);
        $category = Category::findOrFail($id);
        $category->update($req->all());
        session()->flash('flash_mess', 'Category was changed completely');
        return redirect(route('category.edit', $category->id));
    }

    public function destroy($id)
    {
        Category::findOrFail($id)->delete();
        return redirect(route('category.index'));
    }
}

resources/views/category/edit.blade.php
@extends('layouts.view')

@section('table_view')
    @include('errors.list')


    <form action="{{ route('category.update',$category->id) }}" method="post" class="form-horizontal">
        @csrf
        @method('patch')
        <div class="form-group">
            <label class="col-md-2 control-label" for="name">Name of category</label>
            <div class="col-md-10">
                <input type="text" name="name" id="name" value="{{ $category->name }}" class="form-control">
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-2 control-label" for="status">Active</label>
            <div class="col-md-10">
                <input type="checkbox" name="status" id="status"
                       value="{{$category->status}}" {{ ($category->status == 1) ? 'checked' : '' }}>
            </div>
        </div>

        <div class="form-group" style="    display: inline-flex;">

            <div class="col-sm-offset-2 col-sm-6">
                <button type="submit" class="btn btn-primary">Update category</button>

            </div>
            <div class="col-sm-offset-2 col-sm-6" >
                <a class="btn btn-primary" href="{{route('category.index')}}">Category List</a>

            </div>

        </div>

    </form>
@endsection
@push('js')
    <script>
        $('#status').on('click',function () {
            var value = $(this).val();
            if(value === "0" ){
                $('#status').val(1);
            }else{
                $('#status').val(0);
            }
        });

    </script>
@endpush

resources/views/category/index.blade.php
@extends('layouts.view')

@section('table_view')
    @if(!$categories->isEmpty())
        <div class="table-responsive">
            <table class="table table-hover table-bordered">
                <thead>
                <tr>
                    <th>Category name</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
                </thead>
                @foreach($categories as $category)
                    <tr>
                        <td>{{$category->name}}</td>
                        <td>
                            <h4>
                                @if($category->status == 1)
                                    <span class="label label-success">Active
                             @else
                                            <span class="label label-warning">Inactivate


                                </span>
                                @endif
                            </h4>
                        </td>
                        <td>
                            <a class="btn btn-warning" href="{{route('category.edit', [$category->id])}}">Edit</a>
                            <form method="post" action="{{ route('category.destroy', $category->id) }}"
                                  id="delete_{{ $category->id }}" style="display: inline">
                                @method('delete')
                                @csrf
                                <a class="btn btn-danger" id="btn-delete-category"
                                   href="javascript:void(0)"
                                   onclick="document.getElementById('delete_<?=$category->id?>').submit();">
                                    Delete
                                </a>
                            </form>
{{--                            <a class="btn btn-danger" id="btn-delete-category"--}}
{{--                               href="{{route('category.destroy', [$category->id])}}">Delete</a>--}}
                        </td>

                    </tr>
                @endforeach

            </table>
        </div>
    @endif
@endsection

@section('pagination')
    {{$categories->links()}}
@endsection

resources/views/category/new.blade.php
@extends('layouts.view')

@section('table_view')
    @include('errors.list')
    <form action="{{ route('category.store') }}" method="post" class="form-horizontal">
        @csrf
        <div class="form-group">
            <label class="col-md-2 control-label" for="name">Name of category</label>
            <div class="col-md-10">
                <input type="text" name="name" id="name"  class="form-control">
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-2 control-label" for="status">Active</label>
            <div class="col-md-10">
                <input type="checkbox" name="status" id="status" value="0">
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Create category</button>

            </div>
        </div>

    </form>



@endsection
@push('js')
    <script>
        $('#status').on('click',function () {
            var value = $(this).val();
            if(value === "0" ){
                $('#status').val(1);
            }else{
                $('#status').val(0);
            }
        });

    </script>
@endpush