routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Contracts\Auth\Access\Gate;

Route::group(['middleware' => 'web'], function () {

    Route::auth();
    Route::get('/home', function () {
        return redirect('/');
    });

    Route::get('/student/dashboard', function () {
        $user = \Illuminate\Support\Facades\Auth::user();

        if (\Illuminate\Support\Facades\Auth::check()) {
            return view('subject.dashboard', compact('user'));
        } else {
            return redirect()->route('login');
        }

    })->name('student.dashboard');
    Route::get('/', 'HomeController@index');
    Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function () {
        Route::get('/', function () {
            return view('admin.index');
        });
        Route::get('/user', function () {
            return view('admin.user');
        });

        Route::resource('category', 'CategoryController');
        Route::get('results', 'SubjectController@getAllSubjectsResults')->name('subjects.results');
        Route::get('subject', 'SubjectController@getIndex')->name('subject.index');
        Route::get('subject/new', 'SubjectController@getNew')->name('subject.new');
        Route::get('subject/{id}', 'SubjectController@getQuestions')->name('subject.question');
        Route::post('subject/{id}/edit', 'SubjectController@postEditQuestion')->name('subject.question.post.edit');
        Route::post('subject/new', 'SubjectController@postNewSubject')->name('subject.new');
        Route::post('subject/{id}', 'SubjectController@postNewQuestion')->name('subject.post.new.question');
        Route::get('subject/{id}/edit', 'SubjectController@getEdit')->name('subject.question.edit');
        Route::get('subject/{id}/delete', 'SubjectController@getDelete')->name('subject.delete');
        Route::get('subject/{id}/delete/question', 'SubjectController@getDeleteQuestion')->name('subject.question.delete');
        Route::patch('subject/{id}/edit', 'SubjectController@patchEdit')->name('subject.question.patch.edit');
        Route::resource('subject', 'SubjectController', ['except' => ['result', 'save-question', 'before-exam', 'start-exam']]);
        Route::resource('user', 'UserController');
        Route::resource('difficulty', 'DifficultyLevelController');
        Route::resource('score', 'ScoreController');
    });
    Route::group(['prefix' => 'user', 'middleware' => 'user'], function () {
        Route::get('/', function () {
            return redirect('user/get/results');
        })->name('index.home');
        Route::get('result/{id}', 'SubjectController@getShowResultOfSubjectForGuest')->name('result');
        Route::post('subject/save-question-result/{id}', 'SubjectController@postSaveQuestionResult')->name('user.save-question');
        Route::get('subject/{id}/start', 'SubjectController@getBeforeStartTest')->name('before-exam');
        Route::get('subject/{id}/start-test', 'SubjectController@getStartTest')->name('start-exam');
        Route::get('get/results', 'SubjectController@getResults')->name('get.results');
        Route::get('get/progression/level', 'SubjectController@getUserProgressionLevel')->name('user.get.progression.level');


    });
    Route::group(['prefix' => 'teacher', 'middleware' => 'teacher'], function () {


        Route::resource('category', 'CategoryController');
        Route::get('subject', 'SubjectController@getIndex')->name('subject.index');
        Route::get('subject/new', 'SubjectController@getNew')->name('subject.new');
        Route::get('subject/{id}', 'SubjectController@getQuestions')->name('subject.question');
        Route::post('subject/{id}/edit', 'SubjectController@postEditQuestion')->name('subject.question.post.edit');
        Route::post('subject/new', 'SubjectController@postNewSubject')->name('subject.new');
        Route::post('subject/{id}', 'SubjectController@postNewQuestion')->name('subject.post.new.question');
        Route::get('subject/{id}/edit', 'SubjectController@getEdit')->name('subject.question.edit');
        Route::get('subject/{id}/delete', 'SubjectController@getDelete')->name('subject.delete');
        Route::get('subject/{id}/delete/question', 'SubjectController@getDeleteQuestion')->name('subject.question.delete');
        Route::patch('subject/{id}/edit', 'SubjectController@patchEdit')->name('subject.question.patch.edit');
        Route::resource('subject', 'SubjectController', ['except' => ['result', 'save-question', 'before-exam', 'start-exam']]);
        Route::resource('class', 'ClassesController');
        Route::get('get/results', 'SubjectController@getResults')->name('teacher.get.results');

        Route::get('get/progression/level', 'SubjectController@getProgressionLevel')->name('teacher.get.progression.level');


        Route::get('questions/createnew', 'QuestionsController@createnew')->name('questions.createnew');
        Route::post('questions/storequestion', 'QuestionsController@storequestion')->name('questions.storequestion');
        Route::post('questions/updatequestion/{id}', 'QuestionsController@updateQuestion')->name('questions.updatequestion');
        Route::get('questions', 'QuestionsController@Index')->name('questions.index');
        Route::get('questions/edit/{id}', 'QuestionsController@editQuestion')->name('questions.edit');


    });
    Route::get('profile/edit', 'UserController@profileEdit')->name('user.profile.edit');
    Route::post('profile/edit', 'UserController@profileUpdate')->name('user.profile.update');
});

app/Http/Controllers/ScoreController.php
<?php

namespace App\Http\Controllers;

use App\Points;
use Illuminate\Http\Request;

class ScoreController extends Controller
{
    public function index()
    {
        $scores = Points::orderBy('id', 'DESC')->paginate(5);
        $title = 'Score Listing';
        return view('score.index', compact('scores', 'title'));
    }

    public function create()
    {
        $title = "Create New Score";

        return view('score.new',compact('title'));

    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'points' => 'required',
        ], [
            'title.required' => 'Title is required.',
            'points.required' => 'Points is required.',
        ]);

        $score = new Points();
        $score->title = $request->title;
        $score->points = $request->points;
        $score->save();
        session()->flash('flash_mess', 'Score created successfully');
        return redirect()->route('score.index');

    }

    public function edit($id)
    {
        $score = Points::find($id);
        $title = "Edit Score '{$score->title}'";
        return view('score.edit', compact('score','title'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required',
            'points' => 'required',
        ], [
            'title.required' => 'Title is required.',
            'points.required' => 'Points is required.',
        ]);

        $score = Points::find($id);
        $score->title = $request->title;
        $score->points = $request->points;
        $score->save();
        session()->flash('flash_mess', 'Score Updated successfully');
        return redirect()->route('score.index');


    }

    public function destroy($id)
    {

        $score = Points::findOrFail($id);
        $score->delete();

        return redirect()->route('score.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Score has been deleted'
            ]);
    }
}

resources/views/score/edit.blade.php
@extends('layouts.view')

@section('table_view')
    @include('errors.list')


    <form action="{{ route('score.update',$score->id) }}" method="post" class="form-horizontal">
        @csrf
        @method('patch')
        <div class="form-group">
            <label class="col-md-2 control-label" for="title">Title</label>
            <div class="col-md-10">
                <input type="text" name="title" id="title" class="form-control" value="{{ $score->title }}">
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-2 control-label" for="points">Points</label>
            <div class="col-md-10">
                <input type="number" min="1" name="points" id="points" class="form-control" value="{{ $score->points }}">
            </div>
        </div>


        <div class="form-group" style="    display: inline-flex;">

            <div class="col-sm-offset-2 col-sm-6">
                <button type="submit" class="btn btn-primary">Update Score</button>

            </div>
            <div class="col-sm-offset-2 col-sm-6">
                <a class="btn btn-primary" href="{{route('score.index')}}">Score List</a>

            </div>

        </div>

    </form>
@endsection
@push('js')
    <script>

    </script>
@endpush

resources/views/score/index.blade.php
@extends('layouts.view')

@section('table_view')
    @if(!$scores->isEmpty())
        <div class="table-responsive">
            <table class="table table-hover table-bordered">
                <thead>
                <tr>
                        <th>Title</th>
                        <th>Points</th>
                        <th>Action</th>
                </tr>
                </thead>
                @foreach($scores as $score)
                    <tr>
                        <td>{{$score->title}}</td>
                        <td>{{$score->points}}</td>
                        <td>
                            <a class="btn btn-warning" href="{{route('score.edit', [$score->id])}}">Edit</a>
                            <form method="post" action="{{ route('score.destroy', $score->id) }}"
                                  id="delete_{{ $score->id }}" style="display: inline">
                                @method('delete')
                                @csrf
                                <a class="btn btn-danger" id="btn-delete-category"
                                   href="javascript:void(0)"
                                   onclick="document.getElementById('delete_<?=$score->id?>').submit();">
                                    Delete
                                </a>
                            </form>
                        </td>

                    </tr>
                @endforeach

            </table>
        </div>
    @endif
@endsection

@section('pagination')
    {{$scores->links()}}
@endsection

resources/views/score/new.blade.php
@extends('layouts.view')

@section('table_view')
    @include('errors.list')
    <form action="{{ route('score.store') }}" method="post" class="form-horizontal">
        @csrf
        <div class="form-group">
            <label class="col-md-2 control-label" for="title">Title</label>
            <div class="col-md-10">
                <input type="text" name="title" id="title" class="form-control">
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-2 control-label" for="points">Points</label>
            <div class="col-md-10">
                <input type="number" min="1" name="points" id="points" class="form-control">
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Create Score</button>

            </div>
        </div>

    </form>



@endsection
@push('js')

@endpush